# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
    - "514:514"
  environment:
    EX_JAVA_OPTS: "-Xms1g -Xmx1g"
